users:
    admin: ENC[AES256_GCM,data:SYTcOC7eCYyHUHAa2mVQFmHR3/RAXlrFSVob4fq943fWH0mGCH3NMI9MO9FbUX/y4qSG6yu5CROfJO7o,iv:OpQEEN6KmoRidndO4Jp/70EDqyNzQlgtz8rDZZL8XTA=,tag:sbSvN98/uVfkkv3fSj3eAQ==,type:str]
    root: ENC[AES256_GCM,data:2OiMkdmEVdy/lLC0HHoTP/AlTWTPE7DbxAQ30iM9DFHk/ZdmOU9TKRbj5S7A0Xh/WmKhA7AV0985Zz65,iv:YeWMs/a+q+YFrxVEmq/usDI2nrijyKauniYjW/tAa2k=,tag:hn7mkpcuw4sN7RXMshcFSA==,type:str]
id_yamayuri_deployment: ENC[AES256_GCM,data:cuzvYvLLIzLJTsw1y2tQwFpu0XGyqVh++rtIcW9Uy7SlXdXK5x+//CBqHNn+qneea/Qtyhes2ZXK4Pouiszha0nYAnXBIl3fLj3p4G7iaAmJ1El9QIddwdGfNW1ZdMoMA3X46t32zi+xqPuaLbMm3J6SR3E+nCJtB3ZRwYZvb4fu7PFA8r6jcQ1gohXdDlrXPDZ/FdjNrmTw7ExvCOJzd8RH5C0dWscyl3BR3AhTnDXGXw0nTubZNGeAWDRkiGk7Ci2oxTEmU5LVrq9PEd750RRDCHnbS9I6QebXnbvOVhBA7lzio+IHa4rKPHimZdVQo/uyW2w/vdr6jxdTGLylnSTAosMFEbecIkcZlvgpHBFipP+HuuqcEpx7HGEOiJLKgAxoVcRab0pgVjNlc6ZRffkWJt159lfgrOS0mz3oW2zG9i0hmIwUnMSX/8hNizU4/IEg1jpfohQ5IsqGKLbrzFgg897dU7BCctfU1pB6HxsGB43roprfPFmdY3dWyFMUA0El,iv:+IefDdompGw4f4JnAmpXgqsb39q29Ol+owMO9UxpW6g=,tag:iBBT4vEq5pJnxon6tY65CA==,type:str]
porkbun:
    api-key: ENC[AES256_GCM,data:dy+7tuEQBTuQS/Krd7ZD+tqQQCqDEhtEK6N4KLo2IVyfJFngZ+rjAJKTAZ0R5hpEETDuF5dR+Y45JTHg8S2VSOdCSuY=,iv:TO1+cgdc7+p4yBMfvsWQkOsIpjfS6pTzcZ19d/jarto=,tag:tB/j/yKKr0knls5c0uM74Q==,type:str]
    secret-api-key: ENC[AES256_GCM,data:Akc9E8RJgPDhngJYqrJWg/4Efbf+Urh8oT5AF3a88lHth/Fn5UCflVARmt4TO5sWk9m0fS6W6IBhPEDrTiAG/SZ9Tmw=,iv:V4bWMzFEqDio14oIXVQU2hajmDVKbpxheCERZLm5wmc=,tag:lBW5Zrzf481JLvDew4nRZw==,type:str]
sops:
    age:
        - recipient: age1geuk0u6v70d0v9zvzap8dje9dftftx9q57a4rvf0hhwaxueju5aq80ysvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWFdoa0Y2c0VHenphMFAr
            TzF0c2ZHSDdhajMyTC9HR0ptVXlCOUprVnpjCnVuZ0tmdDk0M3hwVTFmUFZtRmF2
            QkFKNEQ5ZW1kbEo5RGJ0ZFRETUxkMTQKLS0tIHFHcVlibkdFYXJMOWV5TWlaRk9M
            Y1ZNbUFLMFhDUm5Gd1hveXhraG9JT2sKBdzSa0SELBmwtpm+OOxmtHQBccu5jqW0
            5xiokr1Ozt+q5YWcxbACSYR/ZrLha7m1PY0h+YvUeWCWKfX4a78pFQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aGN4eVpKMDY5M040Z0Nz
            bWVSQ0lqaUtTb3FsbUk0YVQxZ0NGaDVFOG40CldESldnelFVOVltMS9JTEJXSlZx
            YU8xQ0cxb2JUSWl6QlI4RTU5M25RWUUKLS0tIDdUZ0U3V2xNSjNSRVpwWm80bTdW
            a1Q3SVp5VjB3N1RzNXI0cWdBQVhTYncKBGi1wi/uiVDezei48/Kq2AhQ2a6310Dc
            mOaA0TCs9iVYK3VuN+egLtqH8PwugSlQv1VnspQelOU/fsJpOic2nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-21T21:22:11Z"
    mac: ENC[AES256_GCM,data:VcLVc/BrZDLE6R7q6mh1K9itKTVwmfBJvn3BqupjIRP6A+tDhAzB+aafH3T/NUxUHWzRzeGtghMQbJ8Xy0F12bbx1vFM8A3fj1Z5Z2fDUaBytu2//FSukB62a8RgBL8dXXjgUzg/TmAp7AP5zZUWLhVDX3pqcLj0zaLWJmGM6Zo=,iv:OJlXBh5ee7/q4Z6NVnyxZ0BHdVkdT7aO9QjemsWiA9c=,tag:zNADZUSjTewOEoguQ1f4cw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
