users:
    admin: ENC[AES256_GCM,data:SYTcOC7eCYyHUHAa2mVQFmHR3/RAXlrFSVob4fq943fWH0mGCH3NMI9MO9FbUX/y4qSG6yu5CROfJO7o,iv:OpQEEN6KmoRidndO4Jp/70EDqyNzQlgtz8rDZZL8XTA=,tag:sbSvN98/uVfkkv3fSj3eAQ==,type:str]
    root: ENC[AES256_GCM,data:2OiMkdmEVdy/lLC0HHoTP/AlTWTPE7DbxAQ30iM9DFHk/ZdmOU9TKRbj5S7A0Xh/WmKhA7AV0985Zz65,iv:YeWMs/a+q+YFrxVEmq/usDI2nrijyKauniYjW/tAa2k=,tag:hn7mkpcuw4sN7RXMshcFSA==,type:str]
id_yamayuri_deployment: ENC[AES256_GCM,data:cuzvYvLLIzLJTsw1y2tQwFpu0XGyqVh++rtIcW9Uy7SlXdXK5x+//CBqHNn+qneea/Qtyhes2ZXK4Pouiszha0nYAnXBIl3fLj3p4G7iaAmJ1El9QIddwdGfNW1ZdMoMA3X46t32zi+xqPuaLbMm3J6SR3E+nCJtB3ZRwYZvb4fu7PFA8r6jcQ1gohXdDlrXPDZ/FdjNrmTw7ExvCOJzd8RH5C0dWscyl3BR3AhTnDXGXw0nTubZNGeAWDRkiGk7Ci2oxTEmU5LVrq9PEd750RRDCHnbS9I6QebXnbvOVhBA7lzio+IHa4rKPHimZdVQo/uyW2w/vdr6jxdTGLylnSTAosMFEbecIkcZlvgpHBFipP+HuuqcEpx7HGEOiJLKgAxoVcRab0pgVjNlc6ZRffkWJt159lfgrOS0mz3oW2zG9i0hmIwUnMSX/8hNizU4/IEg1jpfohQ5IsqGKLbrzFgg897dU7BCctfU1pB6HxsGB43roprfPFmdY3dWyFMUA0El,iv:+IefDdompGw4f4JnAmpXgqsb39q29Ol+owMO9UxpW6g=,tag:iBBT4vEq5pJnxon6tY65CA==,type:str]
hass: ENC[AES256_GCM,data:ZY+H2uLrNMih9RBO1agKY2IcgR0CrZ4qpMzCOluX8hapTA0n9V3gT5iQ8EmIc1lLfz7U1owa,iv:TsWj5UWRYmL+KRoINmWrofKYmxXjPo9kYprb2A3AJyY=,tag:m7UltCqeXrwxmNHuHyYHTw==,type:str]
wg0: ENC[AES256_GCM,data:1MEwmoCW/VJYH9Ysm3+Y9vKqtWmfb/jRE1LsMsuYTw4vYA3MCD+jEE2EL8g=,iv:drcNdjR7orNwH410En9x/czSnieTGbed/V40waSQizo=,tag:OrdQhuFLenO3ENdpvfVyUQ==,type:str]
wg1: ENC[AES256_GCM,data:UaBVdMZJfr1tevfbNiaD4NFUdqqniUP5amdMYOAyOVp1g1enLtzQ0drQyDs=,iv:KywgyrlST6ooyNP2TdA3JMTisrl8qMWQ//tDZrrhoBo=,tag:PBq+rXeoX6kLNbza1Sq+iA==,type:str]
porkbun:
    api-key: ENC[AES256_GCM,data:P/Ct/5auib1TiOK6kAsbzH9vE357bYDlWCsSGAnF3OHHCmVO9F87hrE9CFXpL6Jc/Y7//BswC9J0tyocYnVcfNcMgnk=,iv:jZhoYfARTY6lmOQm4Ic7L9jhlzq83xjHVf9MXBfp9eg=,tag:KNi9u7gLfGx8F4J8w59Apw==,type:str]
    secret-api-key: ENC[AES256_GCM,data:ncIQj/+gp1Znp54QN7xiwiGQf9aoROcOdpynC9Bnm6JnJK2pxcK+GEfISwQn3LRLPDcOrgjezP0nN6dQnJT4toXnBug=,iv:hBNUIkhmQnnwPdL+YDpJ1b/y2o5dkaD68oa0yYZKtm0=,tag:hlEKUWf2tKdoOeUtLOkQFw==,type:str]
caddy-env:
    guildId: ENC[AES256_GCM,data:DBTtvIyrKjpKY60tcsoJBdaM,iv:cc9s1qa/6oi2bmnAbwCyooAp/vhoqzdClp+RGuOQndE=,tag:VYe/XmBRhy9Mcq9C6Vh9dw==,type:str]
    botToken: ENC[AES256_GCM,data:v4E8aUF+kzeFI9E+/NbtW6p1jSOxqVEbzOqo1elaqmNMJDlkjOM3srPG9qNXIIzYkGE3shURews/iFalydsX16jGOtrbxEv1,iv:eNWtQs5VNFnaDvNVMpjSdwAzn/x+gVWaAIJu2BVrb/o=,tag:dFDauDzcIjY7bhkGl4JU4A==,type:str]
restic-server: ENC[AES256_GCM,data:VRz4EtP5Z4oCPMFPEkOvj4ywwfX5SYTWtoZPEvVOZtEyC0ESYsJ2uoqkFpN+f/MTia8+Ue9jGdArGrYcj/0Pl/D1xA==,iv:zf1aiN6JE9y5AsZwy0ppOrYXia1KAEzNbAoKOqdKpRo=,tag:Nh9HveQ/FHRB44t4sJUcIQ==,type:str]
zigbee2mqtt:
    network_key: ENC[AES256_GCM,data:oqhsmChba+2OiawhDOWfBKSCxTAdJcCNu8mGyBhq9aaq8jsmqj+ci65EuOwvTgKk+atA4A49DlrosdZ5vVUhPPrSk7rzDQ2ITUx/pVsb+Ew3rcDQtUw47taVqZBlBi2cBHY=,iv:hSjQQc9VVEjyQXiA8rlnpT/f90a9MrGhADruQUzt6mw=,tag:xveo5GBaHKTE4MEmeWkmcA==,type:str]
    pan_id: ENC[AES256_GCM,data:6rMEqtXj,iv:5h9xk/1mdzc92gejyn6c4YOEBvX1zvd+hnIz/PYB/FQ=,tag:dFG+dfz5mb3fVveH+riz2A==,type:str]
    ext_pan_id: ENC[AES256_GCM,data:itEX2v9VNbZ26Yi7/w3Om8jdO5VwACWI8fX0+rNNFNB2ri8+rL1cHTsXjb0yc9UI4Yc=,iv:DHFw5x5/bctHRNJUc4DgZIiK5XCh25RcFwD1vFBB8GY=,tag:flvCBh/neUEhu9gSfyq4bQ==,type:str]
sops:
    age:
        - recipient: age1geuk0u6v70d0v9zvzap8dje9dftftx9q57a4rvf0hhwaxueju5aq80ysvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWFdoa0Y2c0VHenphMFAr
            TzF0c2ZHSDdhajMyTC9HR0ptVXlCOUprVnpjCnVuZ0tmdDk0M3hwVTFmUFZtRmF2
            QkFKNEQ5ZW1kbEo5RGJ0ZFRETUxkMTQKLS0tIHFHcVlibkdFYXJMOWV5TWlaRk9M
            Y1ZNbUFLMFhDUm5Gd1hveXhraG9JT2sKBdzSa0SELBmwtpm+OOxmtHQBccu5jqW0
            5xiokr1Ozt+q5YWcxbACSYR/ZrLha7m1PY0h+YvUeWCWKfX4a78pFQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aGN4eVpKMDY5M040Z0Nz
            bWVSQ0lqaUtTb3FsbUk0YVQxZ0NGaDVFOG40CldESldnelFVOVltMS9JTEJXSlZx
            YU8xQ0cxb2JUSWl6QlI4RTU5M25RWUUKLS0tIDdUZ0U3V2xNSjNSRVpwWm80bTdW
            a1Q3SVp5VjB3N1RzNXI0cWdBQVhTYncKBGi1wi/uiVDezei48/Kq2AhQ2a6310Dc
            mOaA0TCs9iVYK3VuN+egLtqH8PwugSlQv1VnspQelOU/fsJpOic2nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T12:55:56Z"
    mac: ENC[AES256_GCM,data:3l8jfYEgKmKYG1ZXYaubYlW4uDvIoAA4qXqY5fU5J/CpH/LtGI+RoGErrOD/udvr5PLjDCGOJruLO7DBqYNM1OwiZmgWatfX+8K+UMlrreM1HMBjy41VdsmkGlZ/bNYkLh0uOqdrP+ffDgH5qmNIv1ignro06RpTG1KcR3RJ/sY=,iv:T7PUtK3WVXBbYIoApno1EOIO2RCuVY0Vp5UtUSH0YTQ=,tag:fIJRnYiHDKNjaBTlHkdXWA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
