users:
    hana: ENC[AES256_GCM,data:pbmDAAfRE1ncpRHPam2VNkcI6Jj9nDtqq6j6v7zhWAmtS/Rzx6DGTVv5WVJG8/9Nn9GqRF7DX98pMMH5,iv:rbLFc8EQSY0Ou1uZRraLpgF4pOLlNRqAFEVZHCLwdjY=,tag:u3Az/KnecNtdZ7865xuegg==,type:str]
    root: ENC[AES256_GCM,data:pMBAYLLP9Jkyn0x183tnM5sgpL6wolTKbkFlh/2PEiemUS7XvJ+kvijHS8HRDWBUw8evMsCqwSLga11B,iv:Nrs76uGtPPL4tworsEyFPb304jzQjVoKCSNm7I/G8so=,tag:OBpNfwPQTGVDEEFPd3U14g==,type:str]
wg0: ENC[AES256_GCM,data:MoXxUN6GD4mu5MlZ7TCs7I+oaD/tkNEuu6ZCQb3pIZN5cjJelTCJV5yqRvQ=,iv:VjdwvPKfosK2zVFr6siTommmnPq49G8hoGz6X44iQ2A=,tag:MNXzj7KI43jU1tSH6cy39A==,type:str]
sops:
    age:
        - recipient: age14dxfxxluxx2vmh9n77p2278vw8t4rk8yxeq3eh2aww46u7n4mdpqx6upfw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVVRzOTBlZnVOTFl0algv
            UnJiWHd6TjErTXM4Q3RpVXRNZ3JsKzZmQzNVCnhqeEY4REoyTGVwNnlIU2kwME5Q
            VTJ5MVlGTWJiWTd2ZXJxWGlyZzd6dVkKLS0tIG9rellHRnNpU1R2RmZpYlJXeFdm
            eG5rN1NqWnhNcmVmV2NLdk1CdGozWkUK5ggETqJJQkQQB6IO15I0GEfXApWhN2Rn
            F27EIS24kRd9Y+ntiGVqMyqRnBT/uaGbtU2vMRPumjtF5hvJZZS8Tg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1d09LMHVCYmhzZWpUNXd1
            Q0Rjamx1YXl5NjJZYUZaeDlyTEVJS3dlckhrCm1ObWZPVXJUNXE3NlhjSG5JdFY4
            YTMwQnJsbnVxTFdtMmR5WkxwMFRqTUEKLS0tIGk2VTRnUFFGMzJmaEYya21wcnhZ
            SUR3SE5HTFd0dGZiRTJNOXdmL2ljS2sKghGkg2Gti2wzU3re+wS5qJBCo8hW55IQ
            1oLptvLEj5zaSCMGrBpR8zwYh6zdl0DOFMz2mqEhcv5mO3HOJpcAwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T15:57:54Z"
    mac: ENC[AES256_GCM,data:/bXPdd3d3hlG/9VcbJcECTRRyI0HTKVUxjX5109j7P/xU0B52SAdL7UrU0Zj4PmfiOBlx2MopZW2MQQ8eNIY1LyWkfqtAZuNneiMl2ywrWoJgMdfL7kCA2qEskrQxKEBqBJmT15TY1LNe4NRoxHuP+vODCeZ1R2lCkTbJ1MC2YY=,iv:neN4LpndH0OP97nBYXg+5w9uv/hvN36woDz8aOsM3uY=,tag:M7CjI1dmvF4snhYwJfsadw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
